import Head from "next/head";

const NextHead = () => {
  return (
    <Head>
      <title>Mint's ToDoApp</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="../favicon.ico" />
    </Head>
  );
};
export default NextHead;
